name: Build and Release Python Package

on:
  push:
    branches: [ main ]   # always build artifacts on main
    tags:
      - "v*"             # run on tags too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install build
      - run: python -m build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quantum-dice-dist
          path: dist/

      - name: Create GitHub Release (tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
