name: Build and Release Python Package

on:
  push:
    tags:
      - 'v*'          # run only on version tags (e.g. v1.0.0)

# The release step needs this permission
permissions:
  contents: write

# Prevent two runs from racing on the same tag
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Upgrade pip and install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel and sdist
        run: python -m build --sdist --wheel --outdir dist

      - name: Upload dists as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}   # e.g. v1.2.3-rc1 => prerelease
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
