name: Build Python Package

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tool
        run: pip install build

      - name: Build wheel and sdist
        run: python -m build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: quantum-dice-dist
          path: dist/
          
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
