name: Build and Release Python Package

on:
  push:
    tags:
      - 'v*'   # e.g. v1.4.7

# <-- THIS fixes the 403 -->
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build wheel and sdist
        run: python -m build --sdist --wheel --outdir dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*
          generate_release_notes: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
